apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::037320536211:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-Z0ENA28Z51SC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::037320536211:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-26T12:03:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "28359"
  uid: 08f2557c-e005-45df-98d3-b0ea293aa24a
