apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::783520661885:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-VHS4TG5XSCWU
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::783520661885:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-27T11:43:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2052"
  uid: ec580902-e476-4c22-b803-62335638d5a7
